### ISSUE TITLE
Update jdbi.org

### ISSUE THREAD

**Issue by forana** [jdbi/jdbi-docs#17]
[jdbi.org](http://jdbi.org) is reflecting an old state of this repo, likely older than October 2015 (the typo fixed in #15 is still live) - it would be nice to have up-to-date examples available.

**Comment by stevenschlansker** [comment]
hey @brianm I don't think any of us know how to update this -- can you take it?

**Comment by brianm** [comment]
Not sure I so anymore either! Going to close this out in anticipation of moving over to jdbi3 docs :-)
